// Generated from openapi/public-v1.openapi.json (SHA-256: d2135523a13749c6a23d71c24db620076e8b7f4667cdf8ba3cd0c7a8442ce1de).
// Do not edit this file directly. Run: php scripts/generate-public-api-clients.php

export type CorrelationId = string;
export type ReadinessCheckStatus = 'ok' | 'failed';
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject { [key: string]: JsonValue; }
export type QueryParameters = Record<string, string | number | boolean | undefined>;

export interface ApiMeta {
  api_version: 'v1';
  timestamp: string;
  pagination?: {
    current_page: number;
    per_page: number;
    total: number;
    last_page: number;
    [key: string]: JsonValue | undefined;
  };
  idempotent_replay?: boolean;
}

export interface SuccessEnvelope<T> {
  data: T;
  meta: ApiMeta;
  correlation_id: CorrelationId;
}

export interface ErrorEnvelope {
  error: { code: string; message: string; details: Record<string, unknown> };
  meta: ApiMeta;
  correlation_id: CorrelationId;
}

export interface ApiStatusData {
  name: 'Family House Connect API';
  status: 'available';
  surfaces: Array<'public' | 'user' | 'admin'>;
}

export interface HealthData { status: 'ok'; service: 'family-house-connect-api'; }
export interface ReadinessChecks {
  database: ReadinessCheckStatus;
  cache: ReadinessCheckStatus;
  queue: ReadinessCheckStatus;
}
export interface ReadinessData { status: 'ready'; checks: ReadinessChecks; }

export interface PublicApiRequestOptions {
  correlationId?: CorrelationId;
  query?: QueryParameters;
  signal?: AbortSignal;
}

export class PublicApiError extends Error {
  public constructor(public readonly status: number, public readonly envelope: ErrorEnvelope) {
    super(envelope.error.message);
    this.name = 'PublicApiError';
  }
}

export class FamilyHousePublicApiClient {
  public constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = globalThis.fetch,
  ) {}

  public getApiStatus(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<ApiStatusData>> {
    return this.request<SuccessEnvelope<ApiStatusData>>('GET', '/api/v1', options);
  }

  public getHealth(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<HealthData>> {
    return this.request<SuccessEnvelope<HealthData>>('GET', '/api/v1/health', options);
  }

  public getReadiness(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<ReadinessData>> {
    return this.request<SuccessEnvelope<ReadinessData>>('GET', '/api/v1/health/readiness', options);
  }

  public listChurches(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/churches', options);
  }

  public getChurch(church: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', `/api/v1/churches/${encodeURIComponent(church)}`, options);
  }

  public submitHomeChurchApplication(body: JsonObject, idempotencyKey: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('POST', '/api/v1/home-church-applications', options, body, idempotencyKey);
  }

  public listPressPublications(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/press/publications', options);
  }

  public getPressPublication(publicId: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', `/api/v1/press/publications/${encodeURIComponent(publicId)}`, options);
  }

  public downloadPressPublication(publicId: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', `/api/v1/press/publications/${encodeURIComponent(publicId)}/download`, options);
  }

  public listEvents(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/events', options);
  }

  public getEvent(event: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', `/api/v1/events/${encodeURIComponent(event)}`, options);
  }

  public verifyKcaCertificate(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/kca/certificates/verify', options);
  }

  public listMissionLocations(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/mission/locations', options);
  }

  public listMissionCrusades(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/mission/crusades', options);
  }

  public getMissionCrusade(crusade: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', `/api/v1/mission/crusades/${encodeURIComponent(crusade)}`, options);
  }

  public getMapsConfiguration(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/maps/configuration', options);
  }

  public listMapsPlaces(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/maps/places', options);
  }

  public reconcilePublicPaymentWebhook(body: JsonObject, idempotencyKey: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('POST', '/api/v1/finance/webhooks/reconcile', options, body, idempotencyKey);
  }

  public recordPublicPaymentDisputeWebhook(body: JsonObject, idempotencyKey: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('POST', '/api/v1/finance/webhooks/disputes', options, body, idempotencyKey);
  }

  public listContentPages(options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', '/api/v1/content/pages', options);
  }

  public getContentPage(slug: string, options: PublicApiRequestOptions = {}): Promise<SuccessEnvelope<JsonValue>> {
    return this.request<SuccessEnvelope<JsonValue>>('GET', `/api/v1/content/pages/${encodeURIComponent(slug)}`, options);
  }


  private async request<T>(
    method: 'GET' | 'POST',
    path: string,
    options: PublicApiRequestOptions,
    body?: JsonObject,
    idempotencyKey?: string,
  ): Promise<T> {
    const headers: Record<string, string> = { Accept: 'application/json' };
    const url = new URL(path, this.baseUrl);

    for (const [key, value] of Object.entries(options.query ?? {})) {
      if (value !== undefined) url.searchParams.append(key, String(value));
    }

    if (options.correlationId !== undefined) headers['X-Correlation-ID'] = options.correlationId;
    if (body !== undefined) headers['Content-Type'] = 'application/json';
    if (idempotencyKey !== undefined) headers['Idempotency-Key'] = idempotencyKey;

    const response = await this.fetcher(url, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: options.signal,
    });
    const payload = (await response.json()) as T | ErrorEnvelope;

    if (!response.ok) throw new PublicApiError(response.status, payload as ErrorEnvelope);

    return payload as T;
  }
}
