// Generated from openapi/public-v1.openapi.json (SHA-256: 11b8ecbf35bbd51e98e550877bb58f5ce03bb61b022f882f416a5658171b4de8).
// Do not edit this file directly. Run: php scripts/generate-public-api-clients.php

typedef JsonMap = Map<String, Object?>;

abstract interface class PublicApiTransport {
  Future<PublicApiTransportResponse> get(Uri uri, {Map<String, String> headers = const {}});
  Future<PublicApiTransportResponse> post(
    Uri uri, {
    Map<String, String> headers = const {},
    JsonMap body = const {},
  });
}

final class PublicApiTransportResponse {
  const PublicApiTransportResponse({required this.statusCode, required this.body});
  final int statusCode;
  final JsonMap body;
}

final class ApiMeta {
  const ApiMeta({required this.apiVersion, required this.timestamp, required this.raw});
  factory ApiMeta.fromJson(JsonMap json) => ApiMeta(
        apiVersion: json['api_version']! as String,
        timestamp: DateTime.parse(json['timestamp']! as String),
        raw: json,
      );
  final String apiVersion;
  final DateTime timestamp;
  final JsonMap raw;
}

final class SuccessEnvelope<T> {
  const SuccessEnvelope({required this.data, required this.meta, required this.correlationId});
  final T data;
  final ApiMeta meta;
  final String correlationId;
}

final class ApiStatusData {
  const ApiStatusData({required this.name, required this.status, required this.surfaces});
  factory ApiStatusData.fromJson(JsonMap json) => ApiStatusData(
        name: json['name']! as String,
        status: json['status']! as String,
        surfaces: (json['surfaces']! as List<Object?>).cast<String>(),
      );
  final String name;
  final String status;
  final List<String> surfaces;
}

final class HealthData {
  const HealthData({required this.status, required this.service});
  factory HealthData.fromJson(JsonMap json) => HealthData(
        status: json['status']! as String,
        service: json['service']! as String,
      );
  final String status;
  final String service;
}

final class ReadinessChecks {
  const ReadinessChecks({required this.database, required this.cache, required this.queue});
  factory ReadinessChecks.fromJson(JsonMap json) => ReadinessChecks(
        database: json['database']! as String,
        cache: json['cache']! as String,
        queue: json['queue']! as String,
      );
  final String database;
  final String cache;
  final String queue;
}

final class ReadinessData {
  const ReadinessData({required this.status, required this.checks});
  factory ReadinessData.fromJson(JsonMap json) => ReadinessData(
        status: json['status']! as String,
        checks: ReadinessChecks.fromJson(_asMap(json['checks'])),
      );
  final String status;
  final ReadinessChecks checks;
}

final class PublicApiException implements Exception {
  const PublicApiException({
    required this.statusCode,
    required this.code,
    required this.message,
    required this.details,
    required this.correlationId,
  });

  factory PublicApiException.fromResponse(PublicApiTransportResponse response) {
    final error = _asMap(response.body['error']);
    return PublicApiException(
      statusCode: response.statusCode,
      code: error['code']! as String,
      message: error['message']! as String,
      details: _asMap(error['details']),
      correlationId: response.body['correlation_id']! as String,
    );
  }

  final int statusCode;
  final String code;
  final String message;
  final JsonMap details;
  final String correlationId;
}

final class FamilyHousePublicApiClient {
  const FamilyHousePublicApiClient({required this.baseUri, required this.transport});
  final Uri baseUri;
  final PublicApiTransport transport;

  Future<SuccessEnvelope<ApiStatusData>> getApiStatus({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1', correlationId, query: query);
    return _success(response, ApiStatusData.fromJson);
  }

  Future<SuccessEnvelope<HealthData>> getHealth({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/health', correlationId, query: query);
    return _success(response, HealthData.fromJson);
  }

  Future<SuccessEnvelope<ReadinessData>> getReadiness({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/health/readiness', correlationId, query: query);
    return _success(response, ReadinessData.fromJson);
  }

  Future<SuccessEnvelope<Object?>> listChurches({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/churches', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getChurch(String church, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/churches/${Uri.encodeComponent(church)}', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> submitHomeChurchApplication(JsonMap body, String idempotencyKey, {String? correlationId}) async {
    final response = await _request('POST', '/api/v1/home-church-applications', correlationId, body: body, idempotencyKey: idempotencyKey);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listPressPublications({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/press/publications', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getPressPublication(String publicId, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/press/publications/${Uri.encodeComponent(publicId)}', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> downloadPressPublication(String publicId, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/press/publications/${Uri.encodeComponent(publicId)}/download', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listEvents({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/events', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getEvent(String event, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/events/${Uri.encodeComponent(event)}', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> verifyKcaCertificate({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/kca/certificates/verify', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listMissionLocations({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/mission/locations', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listMissionCrusades({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/mission/crusades', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getMissionCrusade(String crusade, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/mission/crusades/${Uri.encodeComponent(crusade)}', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getMapsConfiguration({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/maps/configuration', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listMapsPlaces({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/maps/places', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> reconcilePublicPaymentWebhook(JsonMap body, String idempotencyKey, {String? correlationId}) async {
    final response = await _request('POST', '/api/v1/finance/webhooks/reconcile', correlationId, body: body, idempotencyKey: idempotencyKey);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> recordPublicPaymentDisputeWebhook(JsonMap body, String idempotencyKey, {String? correlationId}) async {
    final response = await _request('POST', '/api/v1/finance/webhooks/disputes', correlationId, body: body, idempotencyKey: idempotencyKey);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listContentPages({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/content/pages', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getContentPage(String slug, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/content/pages/${Uri.encodeComponent(slug)}', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listBibleBooks({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/bible/books', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getBibleChapter(String book, String chapter, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/bible/books/${Uri.encodeComponent(book)}/chapters/${Uri.encodeComponent(chapter)}', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> searchBible({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/bible/search', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> listBiblePlans({JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/bible/plans', correlationId, query: query);
    return _rawSuccess(response);
  }

  Future<SuccessEnvelope<Object?>> getBiblePlan(String plan, {JsonMap query = const {}, String? correlationId}) async {
    final response = await _request('GET', '/api/v1/bible/plans/${Uri.encodeComponent(plan)}', correlationId, query: query);
    return _rawSuccess(response);
  }


  Future<PublicApiTransportResponse> _request(
    String method,
    String path,
    String? correlationId, {
    JsonMap query = const {},
    JsonMap? body,
    String? idempotencyKey,
  }) async {
    final headers = <String, String>{'Accept': 'application/json'};
    var uri = baseUri.resolve(path);
    if (query.isNotEmpty) {
      uri = uri.replace(queryParameters: query.map((key, value) => MapEntry(key, '$value')));
    }
    if (correlationId != null) headers['X-Correlation-ID'] = correlationId;
    if (idempotencyKey != null) headers['Idempotency-Key'] = idempotencyKey;

    final response = method == 'POST'
        ? await transport.post(uri, headers: headers, body: body ?? const {})
        : await transport.get(uri, headers: headers);
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw PublicApiException.fromResponse(response);
    }
    return response;
  }

  SuccessEnvelope<T> _success<T>(
    PublicApiTransportResponse response,
    T Function(JsonMap json) decode,
  ) =>
      SuccessEnvelope<T>(
        data: decode(_asMap(response.body['data'])),
        meta: ApiMeta.fromJson(_asMap(response.body['meta'])),
        correlationId: response.body['correlation_id']! as String,
      );

  SuccessEnvelope<Object?> _rawSuccess(PublicApiTransportResponse response) =>
      SuccessEnvelope<Object?>(
        data: response.body['data'],
        meta: ApiMeta.fromJson(_asMap(response.body['meta'])),
        correlationId: response.body['correlation_id']! as String,
      );
}

JsonMap _asMap(Object? value) => Map<String, Object?>.from(value! as Map);
