<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$configurationPath = $root.'/clients/public-client-generation.json';
$checkOnly = in_array('--check', $argv, true);

try {
    /** @var array{contract: string, operations: array<string, array{method: string, path: string}>, outputs: array{typescript: string, dart: string}} $configuration */
    $configuration = json_decode((string) file_get_contents($configurationPath), true, 512, JSON_THROW_ON_ERROR);
    $contractPath = $root.'/'.$configuration['contract'];
    /** @var array{paths: array<string, array<string, array{operationId?: string}>>} $contract */
    $contract = json_decode((string) file_get_contents($contractPath), true, 512, JSON_THROW_ON_ERROR);
} catch (JsonException $exception) {
    fwrite(STDERR, "Client generation configuration or OpenAPI JSON is invalid: {$exception->getMessage()}\n");
    exit(1);
}

$contractOperations = [];

foreach ($contract['paths'] ?? [] as $path => $pathItem) {
    foreach ($pathItem as $method => $operation) {
        if (! is_array($operation) || ! isset($operation['operationId'])) {
            continue;
        }

        $contractOperations[$operation['operationId']] = [
            'method' => strtoupper($method),
            'path' => $path,
        ];
    }
}

if ($contractOperations !== $configuration['operations']) {
    fwrite(STDERR, "Configured client operations do not exactly match the OpenAPI contract.\n");
    exit(1);
}

$digest = hash_file('sha256', $contractPath);
$outputs = [
    $configuration['outputs']['typescript'] => renderTypeScriptClient($digest, $contractOperations),
    $configuration['outputs']['dart'] => renderDartClient($digest, $contractOperations),
];
$hasDifference = false;

foreach ($outputs as $relativePath => $content) {
    $outputPath = $root.'/'.$relativePath;

    if ($checkOnly) {
        if (! is_file($outputPath) || file_get_contents($outputPath) !== $content) {
            fwrite(STDERR, "Generated client is stale: {$relativePath}\n");
            $hasDifference = true;
        }

        continue;
    }

    $directory = dirname($outputPath);

    if (! is_dir($directory) && ! mkdir($directory, 0775, true) && ! is_dir($directory)) {
        fwrite(STDERR, "Unable to create client output directory: {$directory}\n");
        exit(1);
    }

    file_put_contents($outputPath, $content);
    fwrite(STDOUT, "Generated {$relativePath}\n");
}

exit($hasDifference ? 1 : 0);

/**
 * @param  array<string, array{method: string, path: string}>  $operations
 */
function renderTypeScriptClient(string $digest, array $operations): string
{
    $methods = renderTypeScriptMethods($operations);
    $template = <<<'TYPESCRIPT'
// Generated from openapi/public-v1.openapi.json (SHA-256: {{DIGEST}}).
// Do not edit this file directly. Run: php scripts/generate-public-api-clients.php

export type CorrelationId = string;
export type ReadinessCheckStatus = 'ok' | 'failed';
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject { [key: string]: JsonValue; }
export type QueryParameters = Record<string, string | number | boolean | undefined>;

export interface ApiMeta {
  api_version: 'v1';
  timestamp: string;
  pagination?: {
    current_page: number;
    per_page: number;
    total: number;
    last_page: number;
    [key: string]: JsonValue | undefined;
  };
  idempotent_replay?: boolean;
}

export interface SuccessEnvelope<T> {
  data: T;
  meta: ApiMeta;
  correlation_id: CorrelationId;
}

export interface ErrorEnvelope {
  error: { code: string; message: string; details: Record<string, unknown> };
  meta: ApiMeta;
  correlation_id: CorrelationId;
}

export interface ApiStatusData {
  name: 'Family House Connect API';
  status: 'available';
  surfaces: Array<'public' | 'user' | 'admin'>;
}

export interface HealthData { status: 'ok'; service: 'family-house-connect-api'; }
export interface ReadinessChecks {
  database: ReadinessCheckStatus;
  cache: ReadinessCheckStatus;
  queue: ReadinessCheckStatus;
}
export interface ReadinessData { status: 'ready'; checks: ReadinessChecks; }

export interface PublicApiRequestOptions {
  correlationId?: CorrelationId;
  query?: QueryParameters;
  signal?: AbortSignal;
}

export class PublicApiError extends Error {
  public constructor(public readonly status: number, public readonly envelope: ErrorEnvelope) {
    super(envelope.error.message);
    this.name = 'PublicApiError';
  }
}

export class FamilyHousePublicApiClient {
  public constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = globalThis.fetch,
  ) {}

{{METHODS}}
  private async request<T>(
    method: 'GET' | 'POST',
    path: string,
    options: PublicApiRequestOptions,
    body?: JsonObject,
    idempotencyKey?: string,
  ): Promise<T> {
    const headers: Record<string, string> = { Accept: 'application/json' };
    const url = new URL(path, this.baseUrl);

    for (const [key, value] of Object.entries(options.query ?? {})) {
      if (value !== undefined) url.searchParams.append(key, String(value));
    }

    if (options.correlationId !== undefined) headers['X-Correlation-ID'] = options.correlationId;
    if (body !== undefined) headers['Content-Type'] = 'application/json';
    if (idempotencyKey !== undefined) headers['Idempotency-Key'] = idempotencyKey;

    const response = await this.fetcher(url, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: options.signal,
    });
    const payload = (await response.json()) as T | ErrorEnvelope;

    if (!response.ok) throw new PublicApiError(response.status, payload as ErrorEnvelope);

    return payload as T;
  }
}
TYPESCRIPT;

    return strtr($template, [
        '{{DIGEST}}' => $digest,
        '{{METHODS}}' => $methods,
    ])."\n";
}

/**
 * @param  array<string, array{method: string, path: string}>  $operations
 */
function renderTypeScriptMethods(array $operations): string
{
    $responseTypes = [
        'getApiStatus' => 'ApiStatusData',
        'getHealth' => 'HealthData',
        'getReadiness' => 'ReadinessData',
    ];
    $methods = [];

    foreach ($operations as $operationId => $operation) {
        preg_match_all('/\{([A-Za-z_][A-Za-z0-9_]*)\}/', $operation['path'], $matches);
        $pathParameters = $matches[1];
        $parameters = array_map(fn (string $parameter): string => "{$parameter}: string", $pathParameters);

        if ($operation['method'] === 'POST') {
            $parameters[] = 'body: JsonObject';
            $parameters[] = 'idempotencyKey: string';
        }

        $parameters[] = 'options: PublicApiRequestOptions = {}';
        $path = $operation['path'];

        foreach ($pathParameters as $parameter) {
            $path = str_replace('{'.$parameter.'}', '${encodeURIComponent('.$parameter.')}', $path);
        }

        $pathExpression = $pathParameters === [] ? "'{$path}'" : "`{$path}`";
        $responseType = $responseTypes[$operationId] ?? 'JsonValue';
        $bodyArgument = $operation['method'] === 'POST' ? ', body, idempotencyKey' : '';
        $methods[] = sprintf(
            "  public %s(%s): Promise<SuccessEnvelope<%s>> {\n    return this.request<SuccessEnvelope<%s>>('%s', %s, options%s);\n  }\n",
            $operationId,
            implode(', ', $parameters),
            $responseType,
            $responseType,
            $operation['method'],
            $pathExpression,
            $bodyArgument,
        );
    }

    return implode("\n", $methods)."\n";
}

/**
 * @param  array<string, array{method: string, path: string}>  $operations
 */
function renderDartClient(string $digest, array $operations): string
{
    $methods = renderDartMethods($operations);
    $template = <<<'DART'
// Generated from openapi/public-v1.openapi.json (SHA-256: {{DIGEST}}).
// Do not edit this file directly. Run: php scripts/generate-public-api-clients.php

typedef JsonMap = Map<String, Object?>;

abstract interface class PublicApiTransport {
  Future<PublicApiTransportResponse> get(Uri uri, {Map<String, String> headers = const {}});
  Future<PublicApiTransportResponse> post(
    Uri uri, {
    Map<String, String> headers = const {},
    JsonMap body = const {},
  });
}

final class PublicApiTransportResponse {
  const PublicApiTransportResponse({required this.statusCode, required this.body});
  final int statusCode;
  final JsonMap body;
}

final class ApiMeta {
  const ApiMeta({required this.apiVersion, required this.timestamp, required this.raw});
  factory ApiMeta.fromJson(JsonMap json) => ApiMeta(
        apiVersion: json['api_version']! as String,
        timestamp: DateTime.parse(json['timestamp']! as String),
        raw: json,
      );
  final String apiVersion;
  final DateTime timestamp;
  final JsonMap raw;
}

final class SuccessEnvelope<T> {
  const SuccessEnvelope({required this.data, required this.meta, required this.correlationId});
  final T data;
  final ApiMeta meta;
  final String correlationId;
}

final class ApiStatusData {
  const ApiStatusData({required this.name, required this.status, required this.surfaces});
  factory ApiStatusData.fromJson(JsonMap json) => ApiStatusData(
        name: json['name']! as String,
        status: json['status']! as String,
        surfaces: (json['surfaces']! as List<Object?>).cast<String>(),
      );
  final String name;
  final String status;
  final List<String> surfaces;
}

final class HealthData {
  const HealthData({required this.status, required this.service});
  factory HealthData.fromJson(JsonMap json) => HealthData(
        status: json['status']! as String,
        service: json['service']! as String,
      );
  final String status;
  final String service;
}

final class ReadinessChecks {
  const ReadinessChecks({required this.database, required this.cache, required this.queue});
  factory ReadinessChecks.fromJson(JsonMap json) => ReadinessChecks(
        database: json['database']! as String,
        cache: json['cache']! as String,
        queue: json['queue']! as String,
      );
  final String database;
  final String cache;
  final String queue;
}

final class ReadinessData {
  const ReadinessData({required this.status, required this.checks});
  factory ReadinessData.fromJson(JsonMap json) => ReadinessData(
        status: json['status']! as String,
        checks: ReadinessChecks.fromJson(_asMap(json['checks'])),
      );
  final String status;
  final ReadinessChecks checks;
}

final class PublicApiException implements Exception {
  const PublicApiException({
    required this.statusCode,
    required this.code,
    required this.message,
    required this.details,
    required this.correlationId,
  });

  factory PublicApiException.fromResponse(PublicApiTransportResponse response) {
    final error = _asMap(response.body['error']);
    return PublicApiException(
      statusCode: response.statusCode,
      code: error['code']! as String,
      message: error['message']! as String,
      details: _asMap(error['details']),
      correlationId: response.body['correlation_id']! as String,
    );
  }

  final int statusCode;
  final String code;
  final String message;
  final JsonMap details;
  final String correlationId;
}

final class FamilyHousePublicApiClient {
  const FamilyHousePublicApiClient({required this.baseUri, required this.transport});
  final Uri baseUri;
  final PublicApiTransport transport;

{{METHODS}}
  Future<PublicApiTransportResponse> _request(
    String method,
    String path,
    String? correlationId, {
    JsonMap query = const {},
    JsonMap? body,
    String? idempotencyKey,
  }) async {
    final headers = <String, String>{'Accept': 'application/json'};
    var uri = baseUri.resolve(path);
    if (query.isNotEmpty) {
      uri = uri.replace(queryParameters: query.map((key, value) => MapEntry(key, '$value')));
    }
    if (correlationId != null) headers['X-Correlation-ID'] = correlationId;
    if (idempotencyKey != null) headers['Idempotency-Key'] = idempotencyKey;

    final response = method == 'POST'
        ? await transport.post(uri, headers: headers, body: body ?? const {})
        : await transport.get(uri, headers: headers);
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw PublicApiException.fromResponse(response);
    }
    return response;
  }

  SuccessEnvelope<T> _success<T>(
    PublicApiTransportResponse response,
    T Function(JsonMap json) decode,
  ) =>
      SuccessEnvelope<T>(
        data: decode(_asMap(response.body['data'])),
        meta: ApiMeta.fromJson(_asMap(response.body['meta'])),
        correlationId: response.body['correlation_id']! as String,
      );

  SuccessEnvelope<Object?> _rawSuccess(PublicApiTransportResponse response) =>
      SuccessEnvelope<Object?>(
        data: response.body['data'],
        meta: ApiMeta.fromJson(_asMap(response.body['meta'])),
        correlationId: response.body['correlation_id']! as String,
      );
}

JsonMap _asMap(Object? value) => Map<String, Object?>.from(value! as Map);
DART;

    return strtr($template, [
        '{{DIGEST}}' => $digest,
        '{{METHODS}}' => $methods,
    ])."\n";
}

/**
 * @param  array<string, array{method: string, path: string}>  $operations
 */
function renderDartMethods(array $operations): string
{
    $responseTypes = [
        'getApiStatus' => ['ApiStatusData', 'ApiStatusData.fromJson'],
        'getHealth' => ['HealthData', 'HealthData.fromJson'],
        'getReadiness' => ['ReadinessData', 'ReadinessData.fromJson'],
    ];
    $methods = [];

    foreach ($operations as $operationId => $operation) {
        preg_match_all('/\{([A-Za-z_][A-Za-z0-9_]*)\}/', $operation['path'], $matches);
        $pathParameters = $matches[1];
        $positional = array_map(fn (string $parameter): string => "String {$parameter}", $pathParameters);

        if ($operation['method'] === 'POST') {
            $positional[] = 'JsonMap body';
            $positional[] = 'String idempotencyKey';
        }

        $path = $operation['path'];
        foreach ($pathParameters as $parameter) {
            $path = str_replace('{'.$parameter.'}', '${Uri.encodeComponent('.$parameter.')}', $path);
        }

        $named = $operation['method'] === 'GET'
            ? '{JsonMap query = const {}, String? correlationId}'
            : '{String? correlationId}';
        $signature = implode(', ', [...$positional, $named]);
        $bodyArgument = $operation['method'] === 'POST'
            ? ', body: body, idempotencyKey: idempotencyKey'
            : ', query: query';
        $returnType = $responseTypes[$operationId][0] ?? 'Object?';
        $decode = isset($responseTypes[$operationId])
            ? "return _success(response, {$responseTypes[$operationId][1]});"
            : 'return _rawSuccess(response);';
        $methods[] = sprintf(
            "  Future<SuccessEnvelope<%s>> %s(%s) async {\n    final response = await _request('%s', '%s', correlationId%s);\n    %s\n  }\n",
            $returnType,
            $operationId,
            $signature,
            $operation['method'],
            $path,
            $bodyArgument,
            $decode,
        );
    }

    return implode("\n", $methods)."\n";
}
